Complete to review
tsivarev/vk-community-app-snippet-example pull request #1
Opened 2017-12-13 18:23 UTC by unvir

2017-12-14 07:02 UTC, tsivarev requested changes

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +
лишняя строка

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +        if (page === app.PAGES.EXAM){
пробел

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +
лишняя строка

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +
зачем тут пустой блок?

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +        for(var page in app.PAGES){
пробел

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +            if (question.correctAnswerId === app.examStatus.userAnswers.shift().id){
А зачем это считать здесь и хранить userAnswers если мы можем это сделать на этапе нажатия кнопки "далее" при каждом ответе?

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +            var resultImages = [
Похоже на константу

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +    <!--meta property="og:image" content="images/snippet_img.jpg"-->
А почему закомментировано?

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +                <span id="txt-max-score" class="max-score">3</span></h3>
почему /h3 на этой строке?

2017-12-14 07:02 UTC, tsivarev commented on style.css
> +.wrapper-buttons-control{
codestyle

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +    title: "Математика",
" -> '

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +        <div class="circle">
кажется класс circle не очень подходит сюда. Лучше назвать score или что-то такое

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +                <span id="txt-max-score" class="max-score">3</span></h3>
А если я добавлю в json еще один вопрос?

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +                <span id="txt-score" class="score">0</span>
зачем сокращать как txt?

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +    <a href="#" id="btn-question-submit" class="btn btn-question btn-vk-ui" style="display: none">Отправить</a>
В почему тут сокращаешь как btn, а в wrapper-buttons-control нет?

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +                <label for="btn-show-install-page">
Почему label содержит в себе input? https://www.w3schools.com/tags/tag_label.asp

2017-12-14 07:02 UTC, tsivarev commented on index.html
> +<html lang="en">
lang=en, а весь текст на русском

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +                    'https://vk.com/app' + app.appId,
А почему тут ссылка без groupId?

2017-12-14 07:02 UTC, tsivarev commented on app.js
> +        app.ELEMENTS.INSTALL_APP_BUTTON.addEventListener('click', app.showInstallPage);
А зачем тут отдельная ф-ия? + Зачем инициализировать это listener если показывать страницу не надо

2017-12-14 07:26 UTC, tsivarev requested changes

2017-12-14 07:26 UTC, tsivarev commented on app.js
> +    examStatus: {
Давай откажется от слова exam в пользу test

2017-12-14 14:46 UTC, tsivarev requested changes

2017-12-14 14:46 UTC, tsivarev commented on app.js
> +                var RESULT_IMAGE_IDS = [
нельзя объявлять константы в блоке ф-ии. она должна быть в var

2017-12-14 14:46 UTC, tsivarev commented on app.js
> +                    app.PAGES.EXAM.item.title);
перенос строки

2017-12-14 14:46 UTC, tsivarev commented on index.html
> +    <p class="progress" id="text-title-exam-progress" style="display:none;">Вопрос <b>1</b> из <b>1</b></p>
Убрать Вопрос <b>1</b> из <b>1</b>

2017-12-14 14:46 UTC, tsivarev commented on index.html
> +          content="Приложение \" Мемология\" предложит вам пройти тест и поделиться результатом с друзьями">
Ты научился экранировать " ?

2017-12-19 13:48 UTC, Chaptykov commented on style.css
> +    -moz-border-radius: 50%;
Браузеры, которым нужны префиксы для `border-radius` — это 2010 год. Сейчас префиксы для этого правила можно не использовать.

2017-12-19 13:48 UTC, Chaptykov commented on style.css
> +    text-align: -webkit-center;
Насколько мне известно, такого значения для правила `text-align` не существует.

И при спользовании префиксов, правила с префиксами должны идти перед правилом без префикса.

2017-12-19 13:48 UTC, Chaptykov commented on app.js
> +        var mainContainerElem = document.createElement('div');
Если использовать шаблонизацию на строках вместо манипуляций через DOM, будет меньше кода и понятнее, что происходит.

2017-12-19 13:48 UTC, Chaptykov commented on app.js
> +                app.elements.examProgressTitle.style.display = 'inline-block';
Манипуляции подобного рода лучше делать через CSS-классы. В БЭМ подобные классы называются модификаторами.

Тогда почти всё тело функции заменится на удаление или добавление модификатора в методах `show` и `hide`.

```js
show: function(page) {
  page.classList.remove('page--hidden');
}
hide: function(page) {
  page.classList.add('page--hidden');
}
```

А поведение элементов по этому модификатору описывается в стилях через каскад. Например:

```css
#text-title-test-progress {
  display: inline-block;
}
.page--hidden #text-title-test-progress {
  display: none;
}
```

2017-12-19 14:02 UTC, unvir commented on style.css
> +    -moz-border-radius: 50%;
В safari без префикса не работает. По крайней мере, на iphone se

2017-12-19 14:03 UTC, unvir commented on style.css
> +    text-align: -webkit-center;
Могу ошибаться, но, кажется, сафари не понимал без префикса

2017-12-19 14:39 UTC, Chaptykov commented on style.css
> +    -moz-border-radius: 50%;
Последние версии Сафари, в которых не работает `border-radius` без префикса:

* Для десктопа — 4 (2009 год),
* Для iOS — 3.2 (2010 год)

https://caniuse.com/#search=border-radius

2017-12-19 14:39 UTC, Chaptykov commented on style.css
> +    text-align: -webkit-center;
https://webref.ru/css/text-align

2017-12-19 16:14 UTC, unvir commented on style.css
> +    text-align: -webkit-center;
Проверил, если поставить запись с префиксом вперед, то даже в хроме ломается выравнивание. Полагаю, дело именно в том, что это не правило с префиксом, а значение с префиксом

2017-12-19 17:41 UTC, unvir commented on style.css
> +    text-align: -webkit-center;
![screenshot](https://user-images.githubusercontent.com/14196542/34170705-f9719ffc-e4fc-11e7-87aa-3fb6a9bb6221.png)

2017-12-19 17:43 UTC, unvir commented on style.css
> +    text-align: -webkit-center;
Из более-менее авторитетных источников нашел упоминание только на [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align)

2017-12-21 16:28 UTC, Chaptykov commented on style.css
> +    text-align: -webkit-center;
Я наконец понял, что планировалось сделать этим правилом. И так не стоит делать. 

По ссылке в MDN указано, что это нестандартный синтаксис. Соответственно, любой не-webkit и не-blink браузер должен сломаться, и будет прав.

Для блочного выравнивания есть есть:

* `margin: auto` для блока с заданной шириной
* Flexbox
* Grid, абсолютное позиционирование и прочие инструменты.

Любой из этих вариантов будет надежнее, включая гриды, у которых [не очень хорошая](https://caniuse.com/#feat=css-grid) поддержка.

А еще в данном кейсе необязательно искать способы реализовать именно блочное выравнивание, если [обернуть кнопку](https://jsfiddle.net/jpkqks9x/) в `inline-block`, можно использовать правило `text-align` со значением `center`.

2018-02-02 07:57 UTC, tsivarev approved these changes

2018-02-02 07:57 UTC, merged